#!/bin/bash
# ANSI color--Use these variables to make output in different colors
# and formats. Color names that end with 'f' are foreground colors,
# and those ending with 'b' are background colors.
# for all normal shells

# important do not forget to activate -e for the echo to enable the back slash
# interpretation.
initializeANSI() {
    esc='\033'
    #esc='^['
    # If this doesn't work, enter an ESC directly.
    # Foreground colors
    blackf="${esc}[30m"
    yellowf="${esc}[33m"
    cyanf="${esc}[36m"
    redf="${esc}[31m"
    bluef="${esc}[34m"
    whitef="${esc}[37m"
    greenf="${esc}[32m"
    purplef="${esc}[35m"
    # Background colors
    blackb="${esc}[40m"
    yellowb="${esc}[43m"
    cyanb="${esc}[46m"
    redb="${esc}[41m"
    blueb="${esc}[44m"
    whiteb="${esc}[47m"
    greenb="${esc}[42m"
    purpleb="${esc}[45m"

    # Bold, italic, underline, and inverse style toggles
    boldon="${esc}[1m"
    boldoff="${esc}[22m"
    italicson="${esc}[3m"
    italicsoff="${esc}[23m"
    ulon="${esc}[4m"
    uloff="${esc}[24m"
    invon="${esc}[7m"
    invoff="${esc}[27m"

    reset="${esc}[0m"
}
