#!/usr/bin/env zsh
#
# tmux aliases - sourced from .zshrc (see the aliases_files array there).
# ta/tdc/tn/tk take a session name as their next argument.

alias tl="tmux list-sessions"
alias ta="tmux attach-session -t"
alias td="tmux detach"
alias tdc="tmux detach-client -t"
alias tn="tmux new-session -s"
alias tk="tmux kill-session -t"
alias tks="tmux kill-server"
